openapi: 3.0.1
info:
  title: Test Plugin
  description: A plugin that allows the user to Ping.
  version: 'v1'
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /ping:
    get:
      operationId: getPing
      summary: Get the ping
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPingResponse'

components:
  schemas:
    getPingResponse:
      type: object
      properties:
        msg:
          type: string
          description: the message back from the server
